name: Build and Lint

on:
    pull_request:
    push:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
              with:
                  submodules: 'true'
            - name: Setup pnpm
              uses: pnpm/action-setup@v2
              with:
                  version: latest
            - name: Setup Node.js
              uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4
              with:
                  cache: "pnpm"
            - run: pnpm install
            - run: pnpm build
            - uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v4
              with:
                  name: build
                  path: dist
            - run: pnpm lint --no-fix
