name: Build and Lint

on:
    pull_request:
    push:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
              with:
                  submodules: 'true'
            - name: Setup pnpm
              uses: pnpm/action-setup@v2
              with:
                  version: latest
            - name: Setup Node.js
              uses: actions/setup-node@8f152de45cc393bb48ce5d89d36b731f54556e65 # v4
              with:
                  cache: "pnpm"
            - run: pnpm install
            - run: pnpm build
            - uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3
              with:
                  name: build
                  path: dist
            - run: pnpm lint --no-fix
